### ISSUE TITLE
FiScriptHelper does not request permission

### ISSUE THREAD

**Issue by dnicolson** [Mortennn/FiScript#3]
`FiScriptHelper` does not appear in "Security & Privacy" (the README contains "Security & Anonymity").

Also, when clicking the "Open System Preferences" button the "Extensions" pane in System Preferences opens.

macOS 10.14.2 Beta (18C38b)
FiScript 1.0.1

**Comment by Mortennn** [comment]
I will take a look at soon. Thank you for your PRs😀

**Comment by Mortennn** [comment]
`FiScriptHelper` is a part of the main app, so it is allowed when you allow the main app.

The reason why the "Extensions" pane is shown, is because FiScript has a Finder extension which should be allowed. This is done automatically, but if something goes wrong, you can do it manually. This should be stated more clearly because it is actually quite confusing what should be allowed😅

**Comment by dnicolson** [comment]
Both `FiScriptHelper` and `FiScript` are running but there is no contextual menu. There was never an option to allow the app in "Security & Privacy" as with other unsigned apps.

**Comment by Mortennn** [comment]
I have tested it now and I cannot get it to work either on Mojave. I will try to investigate this issue when I got time. Thank you for reporting!

**Comment by Mortennn** [comment]
I have found that Finder needs to be restarted for the contextual menu to appear. Please let me know if this solves your problem.

**Comment by dnicolson** [comment]
If possible it would be good to hide the "To get FiScript to work properly, you must enable it in System Preferences" if there is already permission granted.

**Comment by Mortennn** [comment]
I agree. I will do that in the near future. Thank you
